---
title: Teaching R to 5th-Middle Graders
author: Sunita Kenner
date: '2017-03-20'
thumbnail: "/img/rolling_bike2.png"
slug: teaching-r-to-5th-middle-graders
categories:
  - Teaching
  - R Tutoring
tags:
  - R
  - ggvis
  - STEM
  - Beginner Statistics
  - Linear Regression
---

Teaching R to 5th graders-Middle Schoolers during the weekend has been both enlightening and humbling.  
Enlightening because kids understand data with context far better than adults; perhaps because they are not encumbered by the `Big Data` noise and always prefer visualization over text.  I've learned to work within the limits of their attention span (so lots of breaks) and interest, cultivating a continuous learning environment versus a competitive one, a "We" versus an "I" approach, and "humbleness" in place "arrogance".  

I, and the 5th graders/Middle Schoolers, would like to thank [RStudio]("https://www.rstudio.com/") (Garrett Grolemund, J.J. Allaire, Hadley Wickham, Roger Oberg) and [Datacamp]("https://www.datacamp.com/home") (Nick Carchedi, Jonathan Cornelissen) for their kindness and all the help, encouragement and support in Tara's and Ben's journey to learning R. Thank you so much.

Here are a few of their projects:

[Grade 5 Project completed for their Science Expo2016]("https://benaracreations2015.shinyapps.io/gr5project/")

[Grade 6 STEM Project]("https://tarak.rbind.io/post/2017/03/26/does-tire-air-pressure-affect-the-rolling-resistance-of-a-mountain-bike/")

[Grade 7 STEM Project]("https://tarak.rbind.io/post/2018/02/22/grade-7-isb-stem-expo-final-assignment/")
